// core_mini_axi_wrapper.sv —— CoreMiniAxi IP 封装顶层
//
// 只引出 时钟(aclk)/复位(aresetn)；AXI(Full 205 信号)/Debug/dm 等其它端口：
//   输入写死无效电平(1'b0)、输出留空
// 注：CoreMiniAxi 本身无 UART/LED 端口（位于 top_coralnpu 层），此处仅时钟/复位
module core_mini_axi_wrapper (
    input  logic aclk,
    input  logic aresetn
);

    CoreMiniAxi u_core (
        .io_aclk(aclk),
        .io_aresetn(aresetn),
        .io_axi_slave_write_addr_ready(),       // 输出留空
        .io_axi_slave_write_addr_valid(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_addr(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_prot(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_id(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_len(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_size(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_burst(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_lock(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_cache(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_qos(1'b0),   // 输入写死无效
        .io_axi_slave_write_addr_bits_region(1'b0),   // 输入写死无效
        .io_axi_slave_write_data_ready(),       // 输出留空
        .io_axi_slave_write_data_valid(1'b0),   // 输入写死无效
        .io_axi_slave_write_data_bits_data(1'b0),   // 输入写死无效
        .io_axi_slave_write_data_bits_last(1'b0),   // 输入写死无效
        .io_axi_slave_write_data_bits_strb(1'b0),   // 输入写死无效
        .io_axi_slave_write_resp_ready(1'b0),   // 输入写死无效
        .io_axi_slave_write_resp_valid(),       // 输出留空
        .io_axi_slave_write_resp_bits_id(),       // 输出留空
        .io_axi_slave_write_resp_bits_resp(),       // 输出留空
        .io_axi_slave_read_addr_ready(),       // 输出留空
        .io_axi_slave_read_addr_valid(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_addr(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_prot(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_id(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_len(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_size(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_burst(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_lock(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_cache(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_qos(1'b0),   // 输入写死无效
        .io_axi_slave_read_addr_bits_region(1'b0),   // 输入写死无效
        .io_axi_slave_read_data_ready(1'b0),   // 输入写死无效
        .io_axi_slave_read_data_valid(),       // 输出留空
        .io_axi_slave_read_data_bits_data(),       // 输出留空
        .io_axi_slave_read_data_bits_id(),       // 输出留空
        .io_axi_slave_read_data_bits_resp(),       // 输出留空
        .io_axi_slave_read_data_bits_last(),       // 输出留空
        .io_axi_master_write_addr_ready(1'b0),   // 输入写死无效
        .io_axi_master_write_addr_valid(),       // 输出留空
        .io_axi_master_write_addr_bits_addr(),       // 输出留空
        .io_axi_master_write_addr_bits_prot(),       // 输出留空
        .io_axi_master_write_addr_bits_id(),       // 输出留空
        .io_axi_master_write_addr_bits_len(),       // 输出留空
        .io_axi_master_write_addr_bits_size(),       // 输出留空
        .io_axi_master_write_addr_bits_burst(),       // 输出留空
        .io_axi_master_write_addr_bits_lock(),       // 输出留空
        .io_axi_master_write_addr_bits_cache(),       // 输出留空
        .io_axi_master_write_addr_bits_qos(),       // 输出留空
        .io_axi_master_write_addr_bits_region(),       // 输出留空
        .io_axi_master_write_data_ready(1'b0),   // 输入写死无效
        .io_axi_master_write_data_valid(),       // 输出留空
        .io_axi_master_write_data_bits_data(),       // 输出留空
        .io_axi_master_write_data_bits_last(),       // 输出留空
        .io_axi_master_write_data_bits_strb(),       // 输出留空
        .io_axi_master_write_resp_ready(),       // 输出留空
        .io_axi_master_write_resp_valid(1'b0),   // 输入写死无效
        .io_axi_master_write_resp_bits_id(1'b0),   // 输入写死无效
        .io_axi_master_write_resp_bits_resp(1'b0),   // 输入写死无效
        .io_axi_master_read_addr_ready(1'b0),   // 输入写死无效
        .io_axi_master_read_addr_valid(),       // 输出留空
        .io_axi_master_read_addr_bits_addr(),       // 输出留空
        .io_axi_master_read_addr_bits_prot(),       // 输出留空
        .io_axi_master_read_addr_bits_id(),       // 输出留空
        .io_axi_master_read_addr_bits_len(),       // 输出留空
        .io_axi_master_read_addr_bits_size(),       // 输出留空
        .io_axi_master_read_addr_bits_burst(),       // 输出留空
        .io_axi_master_read_addr_bits_lock(),       // 输出留空
        .io_axi_master_read_addr_bits_cache(),       // 输出留空
        .io_axi_master_read_addr_bits_qos(),       // 输出留空
        .io_axi_master_read_addr_bits_region(),       // 输出留空
        .io_axi_master_read_data_ready(),       // 输出留空
        .io_axi_master_read_data_valid(1'b0),   // 输入写死无效
        .io_axi_master_read_data_bits_data(1'b0),   // 输入写死无效
        .io_axi_master_read_data_bits_id(1'b0),   // 输入写死无效
        .io_axi_master_read_data_bits_resp(1'b0),   // 输入写死无效
        .io_axi_master_read_data_bits_last(1'b0),   // 输入写死无效
        .io_halted(),       // 输出留空
        .io_fault(),       // 输出留空
        .io_wfi(),       // 输出留空
        .io_irq(1'b0),   // 输入写死无效
        .io_boot_addr(1'b0),   // 输入写死无效
        .io_timer_irq(1'b0),   // 输入写死无效
        .io_software_irq(1'b0),   // 输入写死无效
        .io_debug_en(),       // 输出留空
        .io_debug_addr_0(),       // 输出留空
        .io_debug_addr_1(),       // 输出留空
        .io_debug_addr_2(),       // 输出留空
        .io_debug_addr_3(),       // 输出留空
        .io_debug_inst_0(),       // 输出留空
        .io_debug_inst_1(),       // 输出留空
        .io_debug_inst_2(),       // 输出留空
        .io_debug_inst_3(),       // 输出留空
        .io_debug_cycles(),       // 输出留空
        .io_debug_dbus_valid(),       // 输出留空
        .io_debug_dbus_bits_addr(),       // 输出留空
        .io_debug_dbus_bits_wdata(),       // 输出留空
        .io_debug_dbus_bits_write(),       // 输出留空
        .io_debug_dispatch_0_instFire(),       // 输出留空
        .io_debug_dispatch_0_instAddr(),       // 输出留空
        .io_debug_dispatch_0_instInst(),       // 输出留空
        .io_debug_dispatch_1_instFire(),       // 输出留空
        .io_debug_dispatch_1_instAddr(),       // 输出留空
        .io_debug_dispatch_1_instInst(),       // 输出留空
        .io_debug_dispatch_2_instFire(),       // 输出留空
        .io_debug_dispatch_2_instAddr(),       // 输出留空
        .io_debug_dispatch_2_instInst(),       // 输出留空
        .io_debug_dispatch_3_instFire(),       // 输出留空
        .io_debug_dispatch_3_instAddr(),       // 输出留空
        .io_debug_dispatch_3_instInst(),       // 输出留空
        .io_debug_regfile_writeAddr_0_valid(),       // 输出留空
        .io_debug_regfile_writeAddr_0_bits(),       // 输出留空
        .io_debug_regfile_writeAddr_1_valid(),       // 输出留空
        .io_debug_regfile_writeAddr_1_bits(),       // 输出留空
        .io_debug_regfile_writeAddr_2_valid(),       // 输出留空
        .io_debug_regfile_writeAddr_2_bits(),       // 输出留空
        .io_debug_regfile_writeAddr_3_valid(),       // 输出留空
        .io_debug_regfile_writeAddr_3_bits(),       // 输出留空
        .io_debug_regfile_writeData_0_valid(),       // 输出留空
        .io_debug_regfile_writeData_0_bits_addr(),       // 输出留空
        .io_debug_regfile_writeData_0_bits_data(),       // 输出留空
        .io_debug_regfile_writeData_1_valid(),       // 输出留空
        .io_debug_regfile_writeData_1_bits_addr(),       // 输出留空
        .io_debug_regfile_writeData_1_bits_data(),       // 输出留空
        .io_debug_regfile_writeData_2_valid(),       // 输出留空
        .io_debug_regfile_writeData_2_bits_addr(),       // 输出留空
        .io_debug_regfile_writeData_2_bits_data(),       // 输出留空
        .io_debug_regfile_writeData_3_valid(),       // 输出留空
        .io_debug_regfile_writeData_3_bits_addr(),       // 输出留空
        .io_debug_regfile_writeData_3_bits_data(),       // 输出留空
        .io_debug_regfile_writeData_4_valid(),       // 输出留空
        .io_debug_regfile_writeData_4_bits_addr(),       // 输出留空
        .io_debug_regfile_writeData_4_bits_data(),       // 输出留空
        .io_debug_regfile_writeData_5_valid(),       // 输出留空
        .io_debug_regfile_writeData_5_bits_addr(),       // 输出留空
        .io_debug_regfile_writeData_5_bits_data(),       // 输出留空
        .io_debug_float_writeAddr_valid(),       // 输出留空
        .io_debug_float_writeAddr_bits(),       // 输出留空
        .io_debug_float_writeData_0_valid(),       // 输出留空
        .io_debug_float_writeData_0_bits_addr(),       // 输出留空
        .io_debug_float_writeData_0_bits_data(),       // 输出留空
        .io_debug_float_writeData_1_valid(),       // 输出留空
        .io_debug_float_writeData_1_bits_addr(),       // 输出留空
        .io_debug_float_writeData_1_bits_data(),       // 输出留空
        .io_debug_rb_inst_0_valid(),       // 输出留空
        .io_debug_rb_inst_0_bits_pc(),       // 输出留空
        .io_debug_rb_inst_0_bits_inst(),       // 输出留空
        .io_debug_rb_inst_0_bits_idx(),       // 输出留空
        .io_debug_rb_inst_0_bits_data(),       // 输出留空
        .io_debug_rb_inst_0_bits_trap(),       // 输出留空
        .io_debug_rb_inst_1_valid(),       // 输出留空
        .io_debug_rb_inst_1_bits_pc(),       // 输出留空
        .io_debug_rb_inst_1_bits_inst(),       // 输出留空
        .io_debug_rb_inst_1_bits_idx(),       // 输出留空
        .io_debug_rb_inst_1_bits_data(),       // 输出留空
        .io_debug_rb_inst_1_bits_trap(),       // 输出留空
        .io_debug_rb_inst_2_valid(),       // 输出留空
        .io_debug_rb_inst_2_bits_pc(),       // 输出留空
        .io_debug_rb_inst_2_bits_inst(),       // 输出留空
        .io_debug_rb_inst_2_bits_idx(),       // 输出留空
        .io_debug_rb_inst_2_bits_data(),       // 输出留空
        .io_debug_rb_inst_2_bits_trap(),       // 输出留空
        .io_debug_rb_inst_3_valid(),       // 输出留空
        .io_debug_rb_inst_3_bits_pc(),       // 输出留空
        .io_debug_rb_inst_3_bits_inst(),       // 输出留空
        .io_debug_rb_inst_3_bits_idx(),       // 输出留空
        .io_debug_rb_inst_3_bits_data(),       // 输出留空
        .io_debug_rb_inst_3_bits_trap(),       // 输出留空
        .io_debug_rb_inst_4_valid(),       // 输出留空
        .io_debug_rb_inst_4_bits_pc(),       // 输出留空
        .io_debug_rb_inst_4_bits_inst(),       // 输出留空
        .io_debug_rb_inst_4_bits_idx(),       // 输出留空
        .io_debug_rb_inst_4_bits_data(),       // 输出留空
        .io_debug_rb_inst_4_bits_trap(),       // 输出留空
        .io_debug_rb_inst_5_valid(),       // 输出留空
        .io_debug_rb_inst_5_bits_pc(),       // 输出留空
        .io_debug_rb_inst_5_bits_inst(),       // 输出留空
        .io_debug_rb_inst_5_bits_idx(),       // 输出留空
        .io_debug_rb_inst_5_bits_data(),       // 输出留空
        .io_debug_rb_inst_5_bits_trap(),       // 输出留空
        .io_debug_rb_inst_6_valid(),       // 输出留空
        .io_debug_rb_inst_6_bits_pc(),       // 输出留空
        .io_debug_rb_inst_6_bits_inst(),       // 输出留空
        .io_debug_rb_inst_6_bits_idx(),       // 输出留空
        .io_debug_rb_inst_6_bits_data(),       // 输出留空
        .io_debug_rb_inst_6_bits_trap(),       // 输出留空
        .io_debug_rb_inst_7_valid(),       // 输出留空
        .io_debug_rb_inst_7_bits_pc(),       // 输出留空
        .io_debug_rb_inst_7_bits_inst(),       // 输出留空
        .io_debug_rb_inst_7_bits_idx(),       // 输出留空
        .io_debug_rb_inst_7_bits_data(),       // 输出留空
        .io_debug_rb_inst_7_bits_trap(),       // 输出留空
        .io_dm_req_ready(),       // 输出留空
        .io_dm_req_valid(1'b0),   // 输入写死无效
        .io_dm_req_bits_address(1'b0),   // 输入写死无效
        .io_dm_req_bits_data(1'b0),   // 输入写死无效
        .io_dm_req_bits_op(1'b0),   // 输入写死无效
        .io_dm_rsp_ready(1'b0),   // 输入写死无效
        .io_dm_rsp_valid(),       // 输出留空
        .io_dm_rsp_bits_data(),       // 输出留空
        .io_dm_rsp_bits_op(),       // 输出留空
        .io_te(1'b0)   // 输入写死无效
    );
endmodule
